import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  innerContainer: {
    flex: 1,
  },
  messageList: {
    paddingVertical: 10,
  },
  message: {
    padding: 10,
    marginVertical: 5,
    backgroundColor: "#e6e6e6",
    borderRadius: 10,
    alignSelf: "flex-start",
  },
  myMessage: {
    alignSelf: "flex-end",
    backgroundColor: "#AAA",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#ccc",
  },
  msgInput: {
    flex: 1,
    height: 40,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 10,
    marginRight: 10,
    backgroundColor: "#f9f9f9",
  },
  sendButton: {
    backgroundColor: "#0aa",
    padding: 10,
    borderRadius: 20,
  },
  textInput: {
    borderWidth: 1,
    padding: 10,
    borderRadius: 5,
    flex: 1,
  },
  buttonDisabled: {
    backgroundColor: "grey",
  },
  info: {
    backgroundColor: "#EEE",
    padding: 10,
    borderRadius: 5,
    gap: 8,
  },
  bubble: {
    maxWidth: "80%",
    padding: 10,
    borderRadius: 16,
    marginBottom: 2,
    backgroundColor: "rgba(30,30,30,0.85)",
  },
  myBubble: {
    backgroundColor: "rgba(0,170,170,0.95)",
    alignSelf: "flex-end",
  },
  otherBubble: {
    backgroundColor: "rgba(30,30,30,0.85)",
    alignSelf: "flex-start",
  },
  timestamp: {
    fontSize: 10,
    color: "#fff",
    alignSelf: "flex-end",
    marginTop: 2,
    marginBottom: 4,
    marginHorizontal: 4,
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#0aa",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  avatarText: {
    color: "#fff",
    fontWeight: "bold",
  },
  roomCard: {
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: 16,
    padding: 24,
    marginHorizontal: 8,
    marginTop: 40,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    textAlign: "center",
  },
  roomTitle: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 12,
    color: "#0aa",
    letterSpacing: 1,
    textAlign: "center",
  },
  roomSubtitle: {
    fontSize: 15,
    color: "#555",
    marginBottom: 20,
    textAlign: "center",
  },
  roomButton: {
    backgroundColor: "#0aa",
    paddingVertical: 20,
    paddingHorizontal: 32,
    borderRadius: 8,
    marginVertical: 8,
    alignItems: "center",
    shadowColor: "#0aa",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  roomButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  roomOr: {
    marginVertical: 10,
    color: "#888",
    fontWeight: "600",
    fontSize: 14,
    textAlign: "center",
  },
  roomInputGroup: {
    marginTop: 8,
  },
  roomTextInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#0aa",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 20,
    backgroundColor: "#f9f9f9",
    fontSize: 15,
    marginBottom: 16,
  },
  roomJoinButtonFull: {
    backgroundColor: "#0aa",
    paddingVertical: 20,
    borderRadius: 8,
    alignItems: "center",
    shadowColor: "#0aa",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  dateSeparator: {
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.6)",
    color: "#fff",
    fontSize: 12,
    fontWeight: "bold",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginVertical: 8,
    overflow: "hidden",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
    opacity: 0.7,
  },
  emptyStateText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
  },
});
